### ISSUE TITLE
Deployment Issues

### ISSUE THREAD

**Issue by gfleetwood** [MaxLaumeister/PageCrypt#11]
Hi,

Thanks for this! I was able to get a simple app deployed on repl.it but it didn't work on [GitHub pages](https://github.com/gfleetwood/nullboard) or Netlify. Wondered if you'd have any idea why.

**Comment by MaxLaumeister** [comment]
What wasn't working about it?

My big secret is that PageCrypt is [actually already hosted on GitHub Pages](https://maxlaumeister.github.io/PageCrypt/) - my website maxlaumeister.com just reverse-proxies it - so if it's not working on GitHub Pages for you, it's gotta be some configuration issue, which I would be happy to be a sounding board for.

**Comment by gfleetwood** [comment]
GitHub pages gave me a 404 when it was working before - index.html being deployed from a docs subfolder - without adding the password. Since you ruled out the encryption itself, I looked at your repo and played around a bit:

* Changed docs/index-protected.html to docs/index.html. Didn't work.

*  Copied index.html to the top level folder. Worked.

* Deleted docs/. Worked. This surprised me since GitHub rightly complained in the repo's settings since the folder it was deploying from didn't existed.

* Changed GitHub pages to point to the master branch instead of docs/. Worked. Also removed the complaining.

So got it working but I'm confused about my third try.

**Comment by MaxLaumeister** [comment]
Glad you were able to get it working! I'm going to chalk this one up to the quirkiness of GitHub Pages settings. They've caused me trouble before, too.
