### ISSUE TITLE
Powershell Error

### ISSUE THREAD

**Issue by Ry3yr** [MaxLaumeister/PageCrypt#13]
It seems, using the powershell-implementation gives some error when using:

```

######Before enabling script execution########

PS C:\Users\Desktop> .\Encrypt-StaticHTML.psl -File test..htm1 -Password �-
File C:\Users\Q782\Desktop\Encrypt-StaticHTML.p91 cannot be loaded because the execution of scripts is disabled on this system. 
Please see "get-help about_signing" for more details.
Line:1 Character:25
+ .\Encrypt-StaticHTML.psl <<<< -File test..html -Password �--1234�-�
         + Categorylnfo : NotSpecified: (:) [], PSSecurityException
         + FullyQualifiedErrorId : RuntimeException

#####After enabling script execution#######

PS C:\Users\Q?02\Desktop> .\Encrypt�StaticHTML.psi -File test.htm1 -Password �-�
Unexpected token "octicon" in Expression or Instruction.
IN C:\Users\Q702\Desktop\Encrypt-StaticHTML.p31:320 Character:28
+ <svg class="octicon <<<< octicon-sign-out u-align-middle" viewBox="0
 0 16 17" version="1.1" width="16" height="17" aria-hidden="true"><path fill-ru
le="evenodd" d="M12 9V7H8V5h4V3l4 3-4 3zm-2 3H6V3L2 1h8v3h1Vc0-.55-.45-1-1-1H1
C.45 0 0 .45 8 1v11.38c0 .39.22.73.55.91L6 16.01V13h4c.55 0 1-.45 1-1V8h-1v4z">
</path></svg>
+ Categorylnfo : ParserError: (octicon:String) [], ParseException
+ FullyQualifiedErrorId : UnexpectedToken

```

**Comment by MaxLaumeister** [comment]
I see that what you copied from PowerShell is kind of garbled. There are a lot of unknown characters including question marks and stuff, like this was typed by hand or [OCR'd](https://en.wikipedia.org/wiki/Optical_character_recognition), or there was some sort of bad encoding. Do you know why that is, and is there any chance PageCrypt's scripts could have gotten corrupted in a similar way?

I also noticed `C:\Users\Desktop` in the first powershell script, which is an invalid directory.

**Comment by Ry3yr** [comment]
Yep, it was OCR'd then corrected by hand

That is a typo:
The correct directory is C:\Users\Q702\Desktop

2020-05-04 23:07 GMT+02:00, Maximillian Laumeister <notifications@github.com>:

**Comment by MaxLaumeister** [comment]
It seems like you originally ran it in PowerShell, but your screenshot is running in Command Prompt, which will not work.

Can I see the screenshot of the PowerShell output?

**Comment by Ry3yr** [comment]
Like this ?:
![Screenshot_2020-05-05-11-43-30](https://user-images.githubusercontent.com/17431197/81053749-dca93680-8ec5-11ea-8a22-ce8a7bfaf9e6.jpg)

**Comment by Ry3yr** [comment]
Like this ?:
![Screenshot_2020-05-05-11-46-21](https://user-images.githubusercontent.com/17431197/81053932-285be000-8ec6-11ea-854b-99773a84e428.jpg)

**Comment by MaxLaumeister** [comment]
Please open up your `Encrypt-StaticHTML.psl` file in a text editor, and make sure it matches [the official script](https://raw.githubusercontent.com/MaxLaumeister/PageCrypt/master/PowerShell/Encrypt-StaticHTML.ps1).

The output you're getting only makes any sense to me if you somehow downloaded an HTML page from the GitHub website and renamed it to a `.ps1` file.

**Comment by Ry3yr** [comment]
Ok, did as instructed.
I replaced the file and now this is the current state of affairs.
![Screenshot_2020-05-05-20-49-25](https://user-images.githubusercontent.com/17431197/81114700-d5644600-8f22-11ea-94fb-33da65b553a3.jpg)

**Comment by Ry3yr** [comment]
Made sure to get the file directly this time.
Now Powershell is complaining about some "unsigned file" (?)
![Screenshot_2020-05-05-20-53-28](https://user-images.githubusercontent.com/17431197/81114997-53285180-8f23-11ea-97bc-1ae22080a642.jpg)

**Comment by MaxLaumeister** [comment]
These may help:

https://medium.com/@caiomsouza/fix-for-powershell-script-not-digitally-signed-69f0ed518715

https://stackoverflow.com/questions/9742775/why-is-my-locally-created-script-not-allowed-to-run-under-the-remotesigned-execu

I just googled "ps1 not digitally signed".

**Comment by Ry3yr** [comment]
Tried 
"Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass"

And wow. That is one hell of an ouput.
Attached:
*file.html * file.enc.html (inside zip)
*output.txt

(The encoded file is not working it seems, which hardly surprises - as there are quite some errors)

[output.txt](https://github.com/MaxLaumeister/PageCrypt/files/4583593/output.txt)
[htmls.zip](https://github.com/MaxLaumeister/PageCrypt/files/4583594/htmls.zip)

**Comment by MaxLaumeister** [comment]
According to the readme, you also need `decryptTemplate.html` in the same directory.

**Comment by MaxLaumeister** [comment]
If that doesn't work, then what version of PowerShell are you using? On second look at the readme, it says it's written for v5.

Here's how to check your powershell version:  
https://stackoverflow.com/questions/1825585/determine-installed-powershell-version

**Comment by Ry3yr** [comment]
According to Get-Host: Version 2.0
=> Gotta update that I guess...

About that decryptTemplate.html:
Is that a file inside the github repo of yours, or just an empty html file ?

**Comment by MaxLaumeister** [comment]
It's a file in the repo.

**Comment by Ry3yr** [comment]
Sweet, so:
- Installing PS5
- dropping the Template html inside the folder

=> Made it work.

Perfect :) !
