### ISSUE TITLE
iOS Form submission fault when accessing previously password protected/pagecrypt'd html site

### ISSUE THREAD

**Issue by Ry3yr** [MaxLaumeister/PageCrypt#14]
iOS form submission error

As for the html encryption submit form itself:
It works (for me)  on 
*Windows/Ubuntu (Firefox)
*3DS
*Switch(DNSBrowser) 
*WiiU (builtin browser)
*Android (Chrome)

- however -

 **not on iOS** (iOS9 and  10.3.3), but that is to be expected, as I've
had trouble getting the simplest form submits (https://pastebin.com/MzWCYjeD [test: https://htmledit.squarefree.com])
working on mobileSafari just the same.  
I don't really know what kind of incompatiblity prevents (most likely on apple's site ?) this from working properly, as it works on all other devices I own.

**Comment by Ry3yr** [comment]
Some info on related issues (I suppose):
https://wordpress.org/support/topic/form-wont-submit-on-iphone-but-works-on-android/ https://community.infusionsoft.com/t/solution-make-html5-validation-work-in-safari-ios-osx/32865

**Comment by MaxLaumeister** [comment]
I'm going to see if I can get an iOS / Mobile Safari emulator to try to reproduce this.

**Comment by MaxLaumeister** [comment]
There's nothing off the top of my head that would be causing that, other than Safari 10 being an outdated browser.

I can confirm that I've just tested PageCrypt's demo page on Safari 13.1 on iOS 13.4 and it is working.

Apple is no longer supporting Safari 10, and I can't support it either. Sorry! Please consider forking the project if you want to add support for Safari 10.

**Comment by Ry3yr** [comment]
Ok.
Good to know that it is eventually supported.

Am Dienstag, 5. Mai 2020 schrieb Maximillian Laumeister <
notifications@github.com>:
