### ISSUE TITLE
Point to separate file after authentication instead of transforming the uploaded HTML file

### ISSUE THREAD

**Issue by JordanTranchina** [MaxLaumeister/PageCrypt#16]
Hey Max,

First off fantastic work here, you've saved me the headache of learning about servers for my portfolio site.

I was wondering if it was possible to use PageCrypt but point to a separate HTML file when the password is correct. This would prevent me from having two copies of my files (Unsecured files for reference/updating/developing AND Secured files that have been uploaded/downloaded from your conversion site). Is this possible at all?

Many thanks!

Cheers,
Jordan

**Comment by MaxLaumeister** [comment]
Here's a minimal .html file that you can save, encrypt and use for redirection. Just replace the URL:

```
<!DOCTYPE html>
<html lang="en">
<title>Redirecting...</title>
<script>
    window.top.location.href = "http://www.example.com/hidden-url/";
</script>
```

Spartan, but it validates. Just tested it and it looks like it works!

Please tell me if you have any questions, and I can reopen the issue.
