### ISSUE TITLE
Can this application work with CSS only?

### ISSUE THREAD

**Issue by infracritical** [MaxLaumeister/PageCrypt#17]
Not that I object to using JavaScript, and having the <noscript></noscript> feature helps enforce/re-enforce the user forcibly to use JavaScript, have you thought about a CSS only version of this?  Could it work with CSS only?  Just curious.  -rad

**Comment by MaxLaumeister** [comment]
Hi Rad,

This app definitely cannot work without JavaScript, since it relies on encryption algorithms being executed in the user's web browser.

If you need something that works without JavaScript, i'd consider using something server-side like HTTP basic auth.
