### ISSUE TITLE
File created with pycryptodome cannot be decoded

### ISSUE THREAD

**Issue by fedegiova** [MaxLaumeister/PageCrypt#18]
Hi, 

I've problems in decrypting an html created from the python wrapper, I'm using python 3.8 with pycryptodome on arch linux. 

It turned out the issue was due to padding, because I thought pycryptodome fixed the padding issue in pycrypto. For me the problem get resolved with the following change:

```
diff --git a/python/encrypt.py b/python/encrypt.py
index 700f416..8e03a08 100755
--- a/python/encrypt.py
+++ b/python/encrypt.py
@@ -7,6 +7,7 @@ except:
 	exit(1)
 try:
 	from Crypto import Random
+	from Crypto.Util import Padding
 	from Crypto.Cipher import AES
 except:
 	print("install pycrypto: \"pip3 install pycrypto\"")
@@ -14,6 +15,7 @@ except:
 import os, sys
 from base64 import b64encode
 from getpass import getpass
+import codecs
 
 def main():
 	# sanitize input
@@ -42,14 +44,8 @@ def main():
 	key = PBKDF2(passphrase=passphrase,salt=salt,iterations=100).read(32)
 
 	cipher = AES.new(key, AES.MODE_CBC, IV=iv)
-	padded = data.decode("utf-8", "replace")
-	# workaround for padding issue https://github.com/dlitz/pycrypto/issues/277
-	for i in range(16):
-		try:
-			encrypted = cipher.encrypt(padded.encode("utf8"))
-			break
-		except ValueError:
-			padded += chr(0)
+	padded = Padding.pad(data,16)
+	encrypted = cipher.encrypt(padded)
 
 	projectFolder = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
 	with open(os.path.join(projectFolder, "decryptTemplate.html")) as f:
@@ -61,7 +57,7 @@ def main():
 
 	filename, extension = os.path.splitext(inputfile)
 	outputfile = filename + "-protected" + extension
-	with open(outputfile, 'w') as f:
+	with codecs.open(outputfile, 'w','utf-8-sig') as f:
 		f.write(encryptedDocument)
 	print("File saved to %s"%outputfile)
 
```

**Comment by fedegiova** [comment]
I've also fixed the codec in the output file to produce an uft8 BOM like the online demo tool

**Comment by MaxLaumeister** [comment]
Hi Federico,

You were not the only one to have this issue, see #15. Thank you for submitting this patch to fix it!

The code looks reasonable to me. I just tested it with vanilla PyCrypto and it doesn't seem to work, though (I think vanilla PyCrypto doesn't have a Padding function, at least not in the version I have on my machine.)

So I took a few minutes to write a revised version of your patch that works with vanilla PyCrypto:

https://github.com/MaxLaumeister/PageCrypt/commit/5f2af2fcb30594d2948c8ee13b54f92104167f61

Would you mind testing it with Pycryptodome? If it works there too, I'll merge it!

**Comment by fedegiova** [comment]
Yes, it works for me.

pycryptodome 3.9.8.

Thanks!

**Comment by MaxLaumeister** [comment]
Thank you so much, again Federico! I've just merged the change. 🎉
