### ISSUE TITLE
Change look of password page?

### ISSUE THREAD

**Issue by SparkScratch-P** [MaxLaumeister/PageCrypt#22]
### Hi!
**Thanks** for this awesome tool.

Just something more out of it is what I want. 
Can u pls make the password box customizable, so that it may look like this: [Secret Datatbase](https://sparkscratch-p.github.io/secret-database/)
And allow a background image to be uploaded, like that one. It had a background image in its repo. Just allow one to be uploaded.

**WIll wait for the updates.**
### Thanks again!

**Comment by MaxLaumeister** [comment]
Hi Prodyumna,

You can customize the password box by doing one of two things:

* Use PageCrypt normally, then open up the resulting password protected html file and modify the embedded CSS. By editing the CSS, you can create a single page that looks like whatever you want.

or 

* Download the PageCrypt repo, modify the `decryptTemplate.html` file to add your own CSS, then host the folder using local web server software. This way you will be able to use the tool to create an unlimited amount of new pages using your modified template.

There are no current plans to make a visual editor, so diving into the CSS is the way to do it ;)

**Comment by SparkScratch-P** [comment]
Thanks for the suggestion :) 
From where did u get my name !? Did u do so much of toil through my profile and website?? XD Good Though!

**Comment by MaxLaumeister** [comment]
I did click through to your GitHub profile! I usually like to view those so I can address people properly by their first name.
