### ISSUE TITLE
Mangled unicode characters produced by PowerShell script

### ISSUE THREAD

**Issue by MaxLaumeister** [MaxLaumeister/PageCrypt#28]
PageCrypt has a PowerShell interface that was originally generously contributed by @nialfrancis.

When running a test on the current version of PageCrypt today, I noticed that that unicode characters do not seem to be decrypted properly, presumably due to an encoding issue.

Desired result, as produced by the frontend gui and the python script:

![desired](https://user-images.githubusercontent.com/4030205/153086718-c64b19db-6612-40e3-94b4-3a8754e3c043.png)

Actual result, as produced by the PowerShell script. Note the mangled ⚡ symbol in the decrypted page.

![actual](https://user-images.githubusercontent.com/4030205/153086745-e5eee010-d248-4699-b306-262345911ccb.png)

**Comment by nialfrancis** [comment]
Ahhh I tried to tag the issue in a new PR and failed :(

Quick fix, just force it to read the file as UTF8. I think newer PS versions will by default.

**Comment by MaxLaumeister** [comment]
Thank you for the fix!
