### ISSUE TITLE
How to run this in command prompt?

### ISSUE THREAD

**Issue by animeworld0310** [MaxLaumeister/PageCrypt#34]
Please tell me how I can run this in my Laptop in command prompt

**Comment by MaxLaumeister** [comment]
Please see [`/python/README.md`](https://github.com/MaxLaumeister/PageCrypt/tree/master/python). You'll need to install Python and Pip to get it working.

See also: [This fork of PageCrypt](https://github.com/Greenheart/pagecrypt), which includes more advanced CLI tools.

**Comment by animeworld0310** [comment]
> Please see [`/python/README.md`](https://github.com/MaxLaumeister/PageCrypt/tree/master/python). You'll need to install Python and Pip to get it working.
> 
> See also: [This fork of PageCrypt](https://github.com/Greenheart/pagecrypt), which includes more advanced CLI tools.

Thanks Bro, I worked

**Comment by animeworld0310** [comment]
> Please see [`/python/README.md`](https://github.com/MaxLaumeister/PageCrypt/tree/master/python). You'll need to install Python and Pip to get it working.
> 
> See also: [This fork of PageCrypt](https://github.com/Greenheart/pagecrypt), which includes more advanced CLI tools.

one more thing i wanted to ask in which file i can change design of decryption page

**Comment by MaxLaumeister** [comment]
You'll want to edit the [`decryptTemplate.html`](https://github.com/MaxLaumeister/PageCrypt/blob/master/decryptTemplate.html) file for that!

**Comment by animeworld0310** [comment]
> You'll want to edit the [`decryptTemplate.html`](https://github.com/MaxLaumeister/PageCrypt/blob/master/decryptTemplate.html) file for that!

Thank you so much 🙂
