### ISSUE TITLE
PHP Code?

### ISSUE THREAD

**Issue by PhrostyWatches** [MaxLaumeister/PageCrypt#35]
99.999% of my file is HTML but I have a piece of PHP to automate the copyright year in the footer. I know that it says to upload a HTML file but would it be possible to do the same thing with a PHP file so I don't have to do this every year? :) 

I guess the worst case scenario is to just utilize the div container in the protected file and put the< php echo date("Y"); > there and use that as the footer copyright area.

**Comment by MaxLaumeister** [comment]
I'm sorry to say that PageCrypt-protected pages do not support PHP code.

One option would be to replace your PHP with a snippet of JavaScript, like this:

    <script>document.write(new Date().getFullYear())</script>
