### ISSUE TITLE
Custom styles for PageCrypt?

### ISSUE THREAD

**Issue by slenderstudios** [MaxLaumeister/PageCrypt#36]
Hi!
I see there are no CSS files for PageCrypt, so then how do I change the (no offense) ugly looking default password prompt "window".  

Thanks in advance for any help!

**Comment by MaxLaumeister** [comment]
Hi slenderstudios. PageCrypt's CSS is inline with its HTML. So to change the appearance of my ugly product, you'll need to do one of the following:

* To edit the CSS of one protected page at a time, you can add your styles right before the end `</style>` tag on Line 114 of the final encrypted HTML page.
* To edit the CSS of all future protected pages, you'll need to download PageCrypt and run the program locally using web server software. Add your styles right before the end `</style>` tag on [Line 114 of `decryptTemplate.html`](https://github.com/MaxLaumeister/PageCrypt/blob/master/decryptTemplate.html#L114), then use the local web server to serve PageCrypt, then access it through a web browser. PageCrypt will use the HTML template that now contains your modified styles. Installing and configuring a local web server is beyond the scope of this issue, but there are lots of tutorials out there.

If you want to start with a blank slate for your own CSS, feel free to start removing contents of the existing `<style></style>` block.

**Comment by slenderstudios** [comment]
> Hi slenderstudios. PageCrypt's CSS is inline with its HTML. So to change the appearance of my ugly product, you'll need to do one of the following:
> 
> * To edit the CSS of one protected page at a time, you can add your styles right before the end `</style>` tag on Line 114 of the final encrypted HTML page.
> * To edit the CSS of all future protected pages, you'll need to download PageCrypt and run the program locally using web server software. Add your styles right before the end `</style>` tag on [Line 114 of `decryptTemplate.html`](https://github.com/MaxLaumeister/PageCrypt/blob/master/decryptTemplate.html#L114), then use the local web server to serve PageCrypt, then access it through a web browser. PageCrypt will use the HTML template that now contains your modified styles. Installing and configuring a local web server is beyond the scope of this issue, but there are lots of tutorials out there.
> 
> If you want to start with a blank slate for your own CSS, feel free to start removing contents of the existing `<style></style>` block.

Thanks!
