### ISSUE TITLE
How to change the login form template

### ISSUE THREAD

**Issue by xinoflui** [MaxLaumeister/PageCrypt#37]
Hey there,

I'm looking for some help on how to change the login form template. I already have my own customized login form, which you can find here [ https://codepen.io/finitel/pen/JjeBeNB ]. The thing is, I want to change the original login form and use mine instead, I know how to change it in the already protected HTML file, but I would like to change how the template looks, so I do not have to change it every time I want to set a password on my HTML page.  Any help you can give me with that would be super appreciated.
Thanks!

**Comment by MaxLaumeister** [comment]
Hi XinoFlui,

Please see the linked duplicate issue for instruction on this. Thanks.

-Max

Duplicate of #36

**Comment by MaxLaumeister** [comment]
Duplicate of #36
